apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-container-deployment
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1"
              memory: "256Mi" 
            requests:
              cpu: "0.5" 
              memory: "128Mi" 
